services:
  app:
    build: .
    ports:
      - "3000:3000"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app.rule=Host(`meudevocional.vitordaniel.com`)"
        - "traefik.http.services.app.loadbalancer.server.port=3000"
        - "traefik.http.routers.app.entrypoints=websecure"
        - "traefik.http.routers.app.tls.certresolver=leresolver"
