services:
  app:
    image: vadolasi/meudevocional:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meudevocional.rule=Host(`meudevocional.vitordaniel.com`)"
      - "traefik.http.services.meudevocional.loadbalancer.server.port=3000"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.meudevocional.rule=Host(`meudevocional.vitordaniel.com`)"
        - "traefik.http.services.meudevocional.loadbalancer.server.port=3000"
    networks:
      - traefik

networks:
  traefik:
    external: true
